language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r dev-requirements.txt
  - pip install coveralls
# command to run tests
script:
  - mkdir ../pond
  - git clone https://github.com/esnet/pond.git ../pond/
  - nosetests --verbose --with-coverage --cover-package=pypond
notifications:
  slack: esnet:UcgwMEeTt4IEFs2OZGwFznH2
