language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
# command to install dependencies
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - python setup.py install
  - pip install coveralls
# command to run tests
script:
  - mkdir ../pond
  - git clone https://github.com/esnet/pond.git ../pond/
  - cd ../pond
  - npm install
  - npm run build
  - cd ../pypond
  - nosetests --with-coverage --cover-package=pypond
after_success:
  - coveralls
notifications:
  slack: esnet:UcgwMEeTt4IEFs2OZGwFznH2
